config/routes.rb
MyStore::Application.routes.draw do

  resources :apprentices
  resources :people

end

app/models/apprentice.rb
class Apprentice < Person

end

app/models/apprentice_form.rb
class ApprenticeForm < Reform::Form

  property :title
  property :first_name
  property :middle_name
  property :surname
  property :gender
  property :tyims_id
  property :date_of_birth

  validates :first_name, :surname, :gender, presence: true
  validates :gender, inclusion: { in: ['M', 'F'] }

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  belongs_to :bankable, polymorphic: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_one :bank_account, as: :bankable, dependent: :destroy

  def full_name
    "#{first_name} #{surname}"
  end
end

app/models/person_form.rb
class PersonForm < Reform::Form

  property :title
  property :first_name
  property :middle_name
  property :surname
  property :gender
  property :tyims_id
  property :date_of_birth

  validates :first_name, :surname, :gender, presence: true
  validates :gender, inclusion: { in: ['M', 'F'] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apprentices_controller.rb
class ApprenticesController < ApplicationController

  def index
    @apprentices = Apprentice.all
  end

  def show
    @apprentice = Apprentice.find(params[:id])
  end

  def new
    @apprentice = Apprentice.new
    @form = ApprenticeForm.new(@apprentice)
  end

  def edit
    @apprentice = Apprentice.find(params[:id])
    @form = ApprenticeForm.new(@apprentice)
  end

  def create
    @apprentice = Apprentice.new
    @form = ApprenticeForm.new(@apprentice)

    if @form.validate(params[:apprentice]) && @form.save
      redirect_to apprentices_url, notice: 'Apprentice was successfully created.'
    else
      render action: :new
    end
  end

  def update
    @apprentice = Apprentice.find(params[:id])
    @form = ApprenticeForm.new(@apprentice)

    if @form.validate(params[:apprentice]) && @form.save
      redirect_to apprentices_url, notice: 'Apprentice was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    @apprentice = Apprentice.find(params[:id])
    @apprentice.destroy
    redirect_to apprentices_url
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
    @form = PersonForm.new(@person)
  end

  def edit
    @person = Person.find(params[:id])
    @form = PersonForm.new(@person)
  end

  def create
    @person = Person.new
    @form = PersonForm.new(@person)

    if @form.validate(params[:person]) && @form.save
      redirect_to people_url, notice: 'People was successfully created.'
    else
      render action: :new
    end
  end

  def update
    @person = Person.find(params[:id])
    @form = PersonForm.new(@person)

    if @form.validate(params[:person]) && @form.save
      redirect_to people_url, notice: 'People was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apprentices/index.html.haml
%table.table
  %thead
    %th TYIMS ID
    %th Name
    %th Gender
    %th DOB
    %th.actions
  %tbody
    - @apprentices.each do |app|
      %tr
        %td= app.tyims_id
        %td= app.full_name
        %td= app.gender
        %td= app.date_of_birth
        %td
          .btn-group
            = link_to(icon('eye-open'), app, class: 'btn btn-mini', rel: 'tooltip', title: 'view')
            = link_to(icon('edit'), edit_apprentice_path(app), class: 'btn btn-mini', rel: 'tooltip', title: 'edit')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/edit.html.haml
= simple_form_for(@form) do |f|
  .inputs
    .well
      %h3 Apprentice Details
      = f.input :title,       input_html: { class: 'span2' }
      = f.input :first_name,  input_html: { class: 'span4' }
      = f.input :middle_name, input_html: { class: 'span4' }
      = f.input :surname,     input_html: { class: 'span4' }
      = f.input :gender,      as: :radio_buttons, collection: [['Male', 'M'] ,['Female', 'F']], item_wrapper_class: 'inline'
      = f.input :tyims_id,    as: :string, label: 'TYIMS ID'
      = f.input :date_of_birth,         as: :date_picker, label: 'DOB' do
        = f.input_field :date_of_birth, as: :date_picker, class: 'input_dob', wrapper: false

  .actions
    = f.button :submit, class: 'btn btn-primary', data: { disable_with: 'Processing...' }

app/views/people/index.html.haml
%table.table
  %thead
    %th TYIMS ID
    %th Name
    %th Gender
    %th DOB
    %th.actions
  %tbody
    - @people.each do |app|
      %tr
        %td= app.tyims_id
        %td= app.full_name
        %td= app.gender
        %td= app.date_of_birth
        %td
          .btn-group
            = link_to(icon('eye-open'), app, class: 'btn btn-mini', rel: 'tooltip', title: 'view')
            = link_to(icon('edit'), edit_apprentice_path(app), class: 'btn btn-mini', rel: 'tooltip', title: 'edit')

app/views/people/new.html.haml
= simple_form_for(@form) do |f|
  .inputs
    .well
      %h3 Apprentice Details
      = f.input :title,       input_html: { class: 'span2' }
      = f.input :first_name,  input_html: { class: 'span4' }
      = f.input :middle_name, input_html: { class: 'span4' }
      = f.input :surname,     input_html: { class: 'span4' }
      = f.input :gender,      as: :radio_buttons, collection: [['Male', 'M'] ,['Female', 'F']], item_wrapper_class: 'inline'
      = f.input :tyims_id,    as: :string, label: 'TYIMS ID'
      = f.input :date_of_birth,         as: :date_picker, label: 'DOB' do
        = f.input_field :date_of_birth, as: :date_picker, class: 'input_dob', wrapper: false

  .actions
    = f.button :submit, class: 'btn btn-primary', data: { disable_with: 'Processing...' }